services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
  kafka: 
    image: confluentinc/cp-kafka
    container_name: kafka-kraft
    environment: 
      - KAFKA_PROCESS_ROLES: 'controller, broker'
      - KAFKA_NODE_ID: 1
      - KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kraft-kraft\:29093'
      - KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      - KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOSTNAME://localhost:9092'
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      - KAFKA_JMX_PORT: 9101
      - KAFKA_JMX_HOSTNAME: 'localhost'
      - KAFKA_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://localhost:9092'
    ports: 
      - '9091:9091'
      -  '9101:9101'